/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOptions {
  from: string;
  to: string;
}
export interface TransformResult {
  success: boolean;
  modified: boolean;
  output?: string;
  error?: string;
}
export declare function transformCode(code: string, options: TransformOptions): TransformResult;
