/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AddImport {
  from: string;
  names?: Array<string>;
  defaultName?: string;
}

export interface ImportTransforms {
  replaceSource?: Record<string, string>;
  renameSpecifier?: Record<string, string>;
  removeSpecifier?: Array<string>;
  addImport?: Array<AddImport>;
}

export interface ReplaceTextRule {
  matchText: string;
  replace: string;
  context?: string;
}

export declare function transformCode(code: string, options: TransformOptions): TransformResult;

export interface TransformOptions {
  renames?: Record<string, string>;
  imports?: ImportTransforms;
  removeJsxMemberSuffix?: Array<string>;
  replaceText?: Array<ReplaceTextRule>;
}

export interface TransformResult {
  success: boolean;
  modified: boolean;
  output?: string;
  error?: string;
}
