// Auto-generated by NAPI-RS
export interface TransformOptions {
  renames: Record<string, string>;
}

export interface TransformResult {
  success: boolean;
  modified: boolean;
  output?: string;
  error?: string;
}

export declare function transformCode(code: string, options: TransformOptions): TransformResult;
