// Auto-generated by NAPI-RS

export interface ImportTransforms {
  replaceSource?: Record<string, string>;
  renameSpecifier?: Record<string, string>;
  removeSpecifier?: string[];
  addImport?: AddImport[];
}

export interface AddImport {
  from: string;
  names?: string[];
  defaultName?: string;
}

export interface ReplaceTextRule {
  matchText: string;
  replace: string;
  context?: string;
}

export interface TransformOptions {
  renames?: Record<string, string>;
  imports?: ImportTransforms;
  removeJsxMemberSuffix?: string[];
  replaceText?: ReplaceTextRule[];
}

export interface TransformResult {
  success: boolean;
  modified: boolean;
  output?: string;
  error?: string;
}

export declare function transformCode(code: string, options: TransformOptions): TransformResult;
