/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function transformCode(code: string, options: TransformOptions): TransformResult

export interface TransformOptions {
  from: string
  to: string
}

export interface TransformResult {
  success: boolean
  modified: boolean
  output?: string
  error?: string
}
